### ISSUE TITLE
ImportError: cannot import name 'escape' from 'flask'

### ISSUE THREAD

**Issue by ropelletier** [jamf/JAWA#43]
Received the following error after install. Jawa service will not start

```
Oct 11 13:24:29 cms-jawa1 python3[4739]: Traceback (most recent call last):
Oct 11 13:24:29 cms-jawa1 python3[4739]:   File "/usr/local/jawa/jawa/app.py", line 35, in <module>
Oct 11 13:24:29 cms-jawa1 python3[4739]:     from flask import (Flask, request, render_template,
Oct 11 13:24:29 cms-jawa1 python3[4739]: ImportError: cannot import name 'escape' from 'flask' (/usr/local/jawa/jawa/venv/lib/python3.10/site-packages/flask/__init__.py)
Oct 11 13:24:29 cms-jawa1 systemd[1]: jawa.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 13:24:29 cms-jawa1 systemd[1]: jawa.service: Failed with result 'exit-code'.
Oct 11 13:24:30 cms-jawa1 systemd[1]: jawa.service: Scheduled restart job, restart counter is at 2.
Oct 11 13:24:30 cms-jawa1 systemd[1]: Stopped Jamf Automation & Webhooks Assistant.
Oct 11 13:24:30 cms-jawa1 systemd[1]: Started Jamf Automation & Webhooks Assistant.
Oct 11 13:24:30 cms-jawa1 python3[4740]: Traceback (most recent call last):
Oct 11 13:24:30 cms-jawa1 python3[4740]:   File "/usr/local/jawa/jawa/app.py", line 35, in <module>
Oct 11 13:24:30 cms-jawa1 python3[4740]:     from flask import (Flask, request, render_template,
Oct 11 13:24:30 cms-jawa1 python3[4740]: ImportError: cannot import name 'escape' from 'flask' (/usr/local/jawa/jawa/venv/lib/python3.10/site-packages/flask/__init__.py)
Oct 11 13:24:30 cms-jawa1 systemd[1]: jawa.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 13:24:30 cms-jawa1 systemd[1]: jawa.service: Failed with result 'exit-code'.
Oct 11 13:24:30 cms-jawa1 systemd[1]: jawa.service: Scheduled restart job, restart counter is at 3.
Oct 11 13:24:30 cms-jawa1 systemd[1]: Stopped Jamf Automation & Webhooks Assistant.
Oct 11 13:24:30 cms-jawa1 systemd[1]: Started Jamf Automation & Webhooks Assistant.
```

**Comment by ball42** [comment]
resolved in #44.  Thanks for reporting and for the PR!
